"""initial commerce schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-31 23:30:16.336776
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('featured_image_url', sa.String(length=500), nullable=True),
    sa.Column('category_label', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=150), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banners_placement'), ['placement'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('discount_value > 0', name='ck_coupon_value_positive'),
    sa.CheckConstraint('min_order_amount >= 0', name='ck_coupon_min_order_non_negative'),
    sa.CheckConstraint('used_count >= 0', name='ck_coupon_used_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    op.create_table('delivery_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('free_delivery_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_days', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('delivery_fee >= 0', name='ck_delivery_fee_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('button_label', sa.String(length=100), nullable=True),
    sa.Column('button_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('section_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_sections_section_key'), ['section_key'], unique=True)

    op.create_table('static_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('lead', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_static_pages_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_static_pages_slug'), ['slug'], unique=True)

    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_tagline', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('location_url', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.String(length=200), nullable=True),
    sa.Column('announcement', sa.String(length=300), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('secondary_color', sa.String(length=16), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('order_notifications_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('stored_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=600), nullable=False),
    sa.Column('storage_provider', sa.String(length=16), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_key')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('delivery_area_id', sa.Integer(), nullable=True),
    sa.Column('delivery_area_name', sa.String(length=150), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_orders_subtotal_non_negative'),
    sa.CheckConstraint('total >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['delivery_area_id'], ['delivery_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('track_inventory', sa.Boolean(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_bestseller', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('search_text', sa.String(length=800), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_products_stock_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    op.create_table('package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_product_id', sa.Integer(), nullable=False),
    sa.Column('included_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('display_note', sa.String(length=250), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('package_product_id <> included_product_id', name='ck_package_item_not_self'),
    sa.CheckConstraint('quantity > 0', name='ck_package_item_quantity_positive'),
    sa.ForeignKeyConstraint(['included_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_product_id', 'included_product_id', name='uq_package_item_product')
    )
    with op.batch_alter_table('package_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_items_included_product_id'), ['included_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_items_package_product_id'), ['package_product_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=250), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_option_name')
    )
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_options_product_id'), ['product_id'], unique=False)

    op.create_table('product_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_specifications_product_id'), ['product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_variants_stock_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('variant_description', sa.String(length=200), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('product_option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_option_values_option_id'), ['option_id'], unique=False)

    op.create_table('product_variant_option_values',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('option_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_value_id'], ['product_option_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'option_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variant_option_values')
    with op.batch_alter_table('product_option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_option_values_option_id'))

    op.drop_table('product_option_values')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_specifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_specifications_product_id'))

    op.drop_table('product_specifications')
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_options_product_id'))

    op.drop_table('product_options')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_items_package_product_id'))
        batch_op.drop_index(batch_op.f('ix_package_items_included_product_id'))

    op.drop_table('package_items')
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))

    op.drop_table('order_status_history')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.drop_index(batch_op.f('ix_products_product_type'))
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_public_token'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_phone'))

    op.drop_table('orders')
    op.drop_table('media_assets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('store_settings')
    with op.batch_alter_table('static_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_static_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_static_pages_is_published'))

    op.drop_table('static_pages')
    with op.batch_alter_table('home_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_sections_section_key'))

    op.drop_table('home_sections')
    op.drop_table('hero_slides')
    op.drop_table('delivery_areas')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_placement'))

    op.drop_table('banners')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))

    op.drop_table('articles')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
